### PR TITLE
Update libcxl_tests for prefetch_mode on Radix-mmu mode

### PR DESCRIPTION
**Pull request by vaibhav92**
In  Radix-mmu mode, cxl doesnt support any prefetch mode except 'CXL_PREFAULT_MODE_NONE'. This PR updates the libcxl_tests to correctly check this condition

### CODE REVIEW

**Comment by philippe56** [comment]
Environment variables should be upper case.

**Comment by vaibhav92** [comment]
Hey Philippe,
I have removed the commit in question from the PR as it will need more extensive changes to the Makefile and a different PR in itself.

**Comment by philippe56** [comment]
Two comments regarding set_isRadix():

1. The code is wrong, because isRadix is always set. Thanks to the test:
	if (rd < sizeof(buffer)) {
		perror("Unable to read /proc/cpuinfo");
		return -1;
	} 
We know that rd >= sizeof(buffer) when we evaluate
	isRadix = (rd > 0) ? 1  : 0;

2. Also, the loop is suboptimal. Rather that repeatedly moving chars along, reading one char and comparing buffer and pattern, I suggest to fill and compare buffer and pattern line by line.

**Comment by vaibhav92** [comment]
Hey Philippe, 
1. Good catch. I may have missed a check there in the loop.Will get that fixed.

2. Too many boundary conditions and assumptions to make there e.g max line size. Since file cpuinfo is going to be very small and this is a testcode hence I have took the path to minimize the code needed to implement this.

**Comment by vaibhav92** [comment]
@philippe56 : I have addressed your review comments in the recent revision.

**Comment by philippe56** [comment]
Thanks !

**Pull request merged**
